### ISSUE TITLE
why the max limit live time is 3600s? Can we increase it? 

### ISSUE THREAD

**Issue by CapacitorDev** [aekasitt/cachette#1]
Hi aekasitt,
I want the live time of the cache longer than 3600s. How can we do that?

Also, what's the limit of In-Memory (i.t.o. MB/GB) cache up to? any suggestions? thank you.

**Comment by aekasitt** [comment]
Sorry, I had just seen this.
2 hours seems plenty for caching if you ask me.
The 3600s time-limit exists to prevent foot-gun situations.
In-Memory limit is up to your VM/Docker memory limit.

Do you have a different suggestion for any of these limitations?
